### ISSUE TITLE
Doc tests won't compile with rustc 1.42

### ISSUE THREAD

**Issue by ggreif** [gimli-rs/gimli#488]
```
[nix-shell:~/gimli]$ cargo test

...

   Doc-tests gimli
error[E0514]: found crate `stable_deref_trait` compiled by an incompatible version of rustc
  --> /Users/ggreif/gimli/src/lib.rs:48:9
   |
48 | pub use stable_deref_trait::{CloneStableDeref, StableDeref};
   |         ^^^^^^^^^^^^^^^^^^
   |
   = help: please recompile that crate using this compiler (rustc 1.42.0 (b8cedc004 2020-03-09))
   = note: the following crate versions were found:
           crate `stable_deref_trait` compiled by rustc 1.41.1: /Users/ggreif/gimli/target/debug/deps/libstable_deref_trait-d67f561f714a4168.rlib

error: aborting due to previous error

error: test failed, to rerun pass '--doc'
```

I am using a (mostly) stock
```
[nix-shell:~/gimli]$ rustc --version
rustc 1.42.0 (b8cedc004 2020-03-09)
```

**Comment by philipc** [comment]
That seems like a rustc or cargo bug. Try a `cargo clean` + `cargo update`.

**Comment by ggreif** [comment]
Nope, that didn't help yet, I did
```
cargo update
cargo clean
cargo build
cargo test
```
with the same outcome. I'll watch this.

**Comment by bjorn3** [comment]
Are you sure that `rustc` and `rustdoc` have the same version?

**Comment by ggreif** [comment]
[nix-shell:~/wasmtime]$ rustdoc --version
rustdoc 1.42.0 (b8cedc004 2020-03-09)

[nix-shell:~/wasmtime]$ rustc --version
rustc 1.42.0 (b8cedc004 2020-03-09)

I guess so. But my suspicion is that some tool picks up a different version.

I am running `rustup` from `nixpkgs` and don't have individual
components installed (in theory, of course my nix cache has a bunch of
stuff in it).

**Comment by bjorn3** [comment]
It looks like `cargo` picked `rustc 1.41.1` to compile `stable_deref_trait`, but then used `rustc 1.42.0 (b8cedc004 2020-03-09)` to run rustdoc. Do you have `rustc 1.41.1` somewhere?

**Comment by ggreif** [comment]
```
$ ls -ld /nix/store/*rustc-1.41.1*/
dr-xr-xr-x 3 root nixbld  96 Jan  1  1970
/nix/store/5hl77iigq8fkm4a2hss6hfhbbg90spkk-rustc-1.41.1-doc/
dr-xr-xr-x 5 root nixbld 160 Jan  1  1970
/nix/store/cp7zz8jvz9kfclacff457r7c0ybagpzh-rustc-1.41.1/
```

On my other server (Linux) there is no such thing, and `cargo test` succeeds.

**Comment by ggreif** [comment]
Hmmm, I blew away both with `nix-store --delete` and now
```
$ cargo test
error: could not execute process `/nix/store/cp7zz8jvz9kfclacff457r7c0ybagpzh-rustc-1.41.1/bin/rustc -vV` (never executed)

Caused by:
  No such file or directory (os error 2)
```
so it looks like (the installation of) `rustup` picked up the reference (not using its own `rustc`) and now it's baked in. I'll reinstall `rustup` and retry.

**Comment by bjorn3** [comment]
What does `whereis cargo` return? `~/.cargo/bin/cargo` or some file inside `/nix/store`?

**Comment by ggreif** [comment]
There is no system `cargo`:
```
[nix-shell:~/wasmtime]$ whereis cargo

[nix-shell:~/wasmtime]$ which cargo
/nix/store/pg8393pra5ip2b8ihv4927lnx4mkm589-rustup-1.21.1/bin/cargo

[nix-shell:~/wasmtime]$ ls -l /nix/store/pg8393pra5ip2b8ihv4927lnx4mkm589-rustup-1.21.1/bin/cargo
lrwxr-xr-x 1 root nixbld 6 Jan  1  1970 /nix/store/pg8393pra5ip2b8ihv4927lnx4mkm589-rustup-1.21.1/bin/cargo -> rustup
```

**Comment by ggreif** [comment]
This all is still a mystery to me (reinstalling `~/.rustup/` didn't work), but I strongly doubt that this is a `gimli` problem, so closing.

**Comment by ggreif** [comment]
Okay, now I figured it out. Some `nix-shell` (along the waaaay) injected these gems into my `env`:
```
rustc=/nix/store/cp7zz8jvz9kfclacff457r7c0ybagpzh-rustc-1.41.1
RUSTC=/nix/store/cp7zz8jvz9kfclacff457r7c0ybagpzh-rustc-1.41.1/bin/rustc
```
Hmmm.
